//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle
    {
        public int detailsId { get; set; }
        public Nullable<int> productId { get; set; }
        public Nullable<int> detailsQuantity { get; set; }
        public Nullable<int> detailsPrice { get; set; }
        public Nullable<int> proyectId { get; set; }
        public Nullable<int> userId { get; set; }
    
        public virtual Proyecto Proyecto { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
