//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proyecto
    {
        public Proyecto()
        {
            this.Detalles = new HashSet<Detalle>();
        }
    
        public int proyectId { get; set; }
        public string proyectName { get; set; }
        public string proyectDescription { get; set; }
        public Nullable<int> proyectStock { get; set; }
        public string proyectImage { get; set; }
        public Nullable<int> categoryId { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual ICollection<Detalle> Detalles { get; set; }
    }
}
